dist: trusty
language: java
jdk:
  - openjdk11

cache:
  directories:
    - "~/.m2/repository"
    - "~/.sonar/cache"

before_install:
  - "./.travis/before-install.sh"

install:
  - "./.travis/install.sh"

script:
  - "./.travis/test.sh"

after_success:
  - "./.travis/deploy.sh"
