/*-
 * ==========================LICENSE_START=================================
 * PolyGenesis Platform
 * ========================================================================
 * Copyright (C) 2015 - 2019 Christos Tsakostas, OREGOR LP
 * ========================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ===========================LICENSE_END==================================
 */

package io.polygenesis.annotations.core;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for API methods.
 *
 * @author Christos Tsakostas
 */
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface GFunction {

  /**
   * The name of the method.
   *
   * <p>If not set, it is automatically generated by concatenating the goal and the thing name.
   *
   * <p>If you have more than one methods with the same goal for the same thing, then you should
   * manually the set function name in each one of the methods.
   *
   * @return the string
   */
  String name() default "";

  /**
   * The goal type of a method. e.g. create, collection, etc.
   *
   * @return the string
   */
  GoalType goal();

  /**
   * Thing name.
   *
   * @return the string
   */
  String thingName();
}
